# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '׷ާĦ.ui'
#
# Created: Tue Jan  1 19:20:10 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(705, 303)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.akiL = QtWidgets.QLabel(self.centralwidget)
        self.akiL.setGeometry(QtCore.QRect(30, 11, 83, 32))
        self.akiL.setObjectName("akiL")
        self.aksL = QtWidgets.QLabel(self.centralwidget)
        self.aksL.setGeometry(QtCore.QRect(8, 55, 104, 32))
        self.aksL.setObjectName("aksL")
        self.dnL = QtWidgets.QLabel(self.centralwidget)
        self.dnL.setGeometry(QtCore.QRect(40, 100, 74, 32))
        self.dnL.setObjectName("dnL")
        self.riL = QtWidgets.QLabel(self.centralwidget)
        self.riL.setGeometry(QtCore.QRect(52, 145, 63, 32))
        self.riL.setObjectName("riL")
        self.rtL = QtWidgets.QLabel(self.centralwidget)
        self.rtL.setGeometry(QtCore.QRect(2, 189, 104, 32))
        self.rtL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rtL.setObjectName("rtL")
        self.AKI = QtWidgets.QLineEdit(self.centralwidget)
        self.AKI.setGeometry(QtCore.QRect(121, 8, 288, 40))
        self.AKI.setObjectName("AKI")
        self.AKS = QtWidgets.QLineEdit(self.centralwidget)
        self.AKS.setGeometry(QtCore.QRect(120, 52, 288, 40))
        self.AKS.setObjectName("AKS")
        self.DN = QtWidgets.QLineEdit(self.centralwidget)
        self.DN.setGeometry(QtCore.QRect(120, 97, 288, 40))
        self.DN.setObjectName("DN")
        self.RI = QtWidgets.QLineEdit(self.centralwidget)
        self.RI.setGeometry(QtCore.QRect(120, 142, 288, 40))
        self.RI.setObjectName("RI")
        self.RT = QtWidgets.QLineEdit(self.centralwidget)
        self.RT.setGeometry(QtCore.QRect(120, 186, 288, 40))
        self.RT.setObjectName("RT")
        self.RicB = QtWidgets.QPushButton(self.centralwidget)
        self.RicB.setGeometry(QtCore.QRect(8, 239, 102, 40))
        self.RicB.setObjectName("RicB")
        self.StartB = QtWidgets.QPushButton(self.centralwidget)
        self.StartB.setGeometry(QtCore.QRect(120, 239, 88, 40))
        self.StartB.setObjectName("StartB")
        self.AboutB = QtWidgets.QPushButton(self.centralwidget)
        self.AboutB.setGeometry(QtCore.QRect(316, 256, 88, 24))
        self.AboutB.setObjectName("AboutB")
        self.DebugC = QtWidgets.QCheckBox(self.centralwidget)
        self.DebugC.setGeometry(QtCore.QRect(320, 235, 88, 24))
        self.DebugC.setObjectName("DebugC")
        self.StopB = QtWidgets.QPushButton(self.centralwidget)
        self.StopB.setGeometry(QtCore.QRect(218, 239, 88, 40))
        self.StopB.setObjectName("StopB")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(424, 8, 272, 272))
        self.groupBox.setObjectName("groupBox")
        self.Debug = QtWidgets.QTextEdit(self.groupBox)
        self.Debug.setGeometry(QtCore.QRect(4, 16, 264, 248))
        self.Debug.setReadOnly(True)
        self.Debug.setObjectName("Debug")
        #Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        #Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)
        Main.setTabOrder(self.AKI, self.AKS)
        Main.setTabOrder(self.AKS, self.DN)
        Main.setTabOrder(self.DN, self.RI)
        Main.setTabOrder(self.RI, self.RT)
        Main.setTabOrder(self.RT, self.RicB)
        Main.setTabOrder(self.RicB, self.StartB)
        Main.setTabOrder(self.StartB, self.StopB)
        Main.setTabOrder(self.StopB, self.DebugC)
        Main.setTabOrder(self.DebugC, self.AboutB)
        Main.setTabOrder(self.AboutB, self.Debug)
        print self.DebugC
		
    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "阿里云API-DDNS"))
        self.akiL.setText(_translate("Main", "Access Key ID"))
        self.aksL.setText(_translate("Main", "Access Key Secret"))
        self.dnL.setText(_translate("Main", "Domain Name"))
        self.riL.setText(_translate("Main", "Record ID"))
        self.rtL.setText(_translate("Main", "Record Type"))
        self.RicB.setText(_translate("Main", "不知道RecordID？"))
        self.StartB.setText(_translate("Main", "开始"))
        self.AboutB.setText(_translate("Main", "关于"))
        self.DebugC.setText(_translate("Main", "调试输出"))
        self.StopB.setText(_translate("Main", "停止"))
        self.groupBox.setTitle(_translate("Main", "调试输出"))

